"""create tables infogrid

Revision ID: 0bbf3875f68b
Revises: 
Create Date: 2025-01-11 23:36:30.341628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbf3875f68b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estado_atual', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_databases_id'), 'databases', ['id'], unique=False)
    op.create_table('responsaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_responsaveis_id'), 'responsaveis', ['id'], unique=False)
    op.create_table('topicos_kafka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estado_atual', sa.String(length=50), nullable=True),
    sa.Column('conformidade', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topicos_kafka_id'), 'topicos_kafka', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('colunas_topicos_kafka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_dado', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('topico_kafka_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topico_kafka_id'], ['topicos_kafka.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colunas_topicos_kafka_id'), 'colunas_topicos_kafka', ['id'], unique=False)
    op.create_table('registros_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('conjunto_dados', sa.String(length=255), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('finalidade_uso', sa.Text(), nullable=False),
    sa.Column('permissoes_concedidas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_acesso_id'), 'registros_acesso', ['id'], unique=False)
    op.create_table('responsaveis_databases',
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.PrimaryKeyConstraint('responsavel_id', 'database_id')
    )
    op.create_table('responsaveis_topicos_kafka',
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('topico_kafka_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.ForeignKeyConstraint(['topico_kafka_id'], ['topicos_kafka.id'], ),
    sa.PrimaryKeyConstraint('responsavel_id', 'topico_kafka_id')
    )
    op.create_table('tabelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.Column('estado_atual', sa.String(length=50), nullable=True),
    sa.Column('qualidade', sa.String(length=50), nullable=True),
    sa.Column('conformidade', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tabelas_id'), 'tabelas', ['id'], unique=False)
    op.create_table('colunas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_dado', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tabela_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tabela_id'], ['tabelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colunas_id'), 'colunas', ['id'], unique=False)
    op.create_table('responsaveis_tabelas',
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('tabela_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.ForeignKeyConstraint(['tabela_id'], ['tabelas.id'], ),
    sa.PrimaryKeyConstraint('responsavel_id', 'tabela_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsaveis_tabelas')
    op.drop_index(op.f('ix_colunas_id'), table_name='colunas')
    op.drop_table('colunas')
    op.drop_index(op.f('ix_tabelas_id'), table_name='tabelas')
    op.drop_table('tabelas')
    op.drop_table('responsaveis_topicos_kafka')
    op.drop_table('responsaveis_databases')
    op.drop_index(op.f('ix_registros_acesso_id'), table_name='registros_acesso')
    op.drop_table('registros_acesso')
    op.drop_index(op.f('ix_colunas_topicos_kafka_id'), table_name='colunas_topicos_kafka')
    op.drop_table('colunas_topicos_kafka')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_topicos_kafka_id'), table_name='topicos_kafka')
    op.drop_table('topicos_kafka')
    op.drop_index(op.f('ix_responsaveis_id'), table_name='responsaveis')
    op.drop_table('responsaveis')
    op.drop_index(op.f('ix_databases_id'), table_name='databases')
    op.drop_table('databases')
    # ### end Alembic commands ###
