"""Adicionando Atributos em Database e responsaveis

Revision ID: 77d3f580878a
Revises: 0bbf3875f68b
Create Date: 2025-01-12 17:20:54.401770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d3f580878a'
down_revision: Union[str, None] = '0bbf3875f68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
