"""Auto incremento no indexs

Revision ID: 7e6e310343b5
Revises: 8287b2bbaafb
Create Date: 2025-01-13 21:32:53.136843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6e310343b5'
down_revision: Union[str, None] = '8287b2bbaafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'databases', ['nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'databases', type_='unique')
    # ### end Alembic commands ###
